#-----------------------------#
#     Major Site Settings     #
#-----------------------------#
url: http://rexmac.com
title: rexmac.com
description: "Rex McConnell's place on the world-wide-web, with tutorials, notes, and ramblings on computer programming, web development, and other topics"
author:
  name: Rex McConnell
  github: rexmac
  twitter: _rexmac
analytics:
  provider: google
  google:
    tracking_id: 'UA-26354182-1'

#---------------------------------------#
#             Blog Settings             #
#---------------------------------------#
paginate: 10                            # Posts per page on the blog index
pagination_dir: blog                    # Directory base for pagination URLs, e.g., /blog/page/2/
permalink: /blog/:title                 # URL structure for blog posts
recent_posts: 5                         # Posts in the sidebar Recent Posts section
excerpt_link: "Continue reading &rarr;" # "Continue reading" link text at the bottom of excerpted articles
category_dir: blog/categories           # Directory base for category URLs, e.g., /blog/categories/
tag_dir: blog/tags                      # Directory base for tag URLs, e.g., /blog/tags/

#-----------------------------#
#       Jekyll Settings       #
#-----------------------------#
source: src
destination: public
pygments: true
markdown: kramdown

#-----------------------------#
#       Build Settings        #
#-----------------------------#
include: [".htaccess"]
exclude: [
  "CNAME",
  "config.rb",
  "Gemfile",
  "Gemfile.lock",
  "Guardfile",
  "Rakefile",
  "README.md",
  "resolutionizr.html",
  "rexmac.com.sublime-project",
  "rexmac.com.sublime-workspace",
  "sass"
]
js: [
  "site.min.js": [
    "js/libs/sprintf.min.js",
    "js/libs/bootstrap-transition.js",
    "js/libs/bootstrap-collapse.js",
    "js/libs/bootstrap-tooltip.js",
    "js/libs/imageFlip.js",
    "js/libs/jquery.cookie.js",
    "js/libs/jquery.fcbkcomplete.js",
    "js/libs/jquery.notifier.js",
    "js/libs/jquery.showLoading.js",
    "js/libs/jquery.treemap.js",
    "js/libs/jquery.validate.js",
    "js/libs/fayer.js",
    "js/_rexmac.js"
  ]
]
