#-----------------------------#
#     Major Site Settings     #
#-----------------------------#
url: http://rexmac.com
domain: rexmac.com
title: rexmac.com
description: "Rex McConnell's place on the world-wide-web, with tutorials, notes, and ramblings on computer programming, web development, and other topics"
author:
  name: Rex McConnell
  github: rexmac
  gplus: RexMcConnell
  twitter: _rexmac
analytics:
  provider: google
  google:
    tracking_id: 'UA-26354182-1'
rsync:
  user: rexmac
  host: rexmac.com
  path: ~/public_html/

#---------------------------------------#
#             Blog Settings             #
#---------------------------------------#
paginate: 10                            # Posts per page on the blog index
paginate_path: "blog/page:num"          # Path for paginated blog index pages
pagination_dir: blog                    # Directory base for pagination URLs, e.g., /blog/page/2/
permalink: /blog/:title                 # URL structure for blog posts
recent_posts: 5                         # Posts in the sidebar Recent Posts section
excerpt_link: "Continue reading &rarr;" # "Continue reading" link text at the bottom of excerpted articles
category_dir: blog/category             # Directory base for category URLs, e.g., /blog/categories/
tag_dir: blog/tag                       # Directory base for tag URLs, e.g., /blog/tags/

#-----------------------------#
#       Jekyll Settings       #
#-----------------------------#
source: src
destination: public
pygments: true
markdown: kramdown
relative_permalinks: true

#-----------------------------#
#       Build Settings        #
#-----------------------------#
include: [".htaccess"]
exclude: [
  "resolutionizr.html",
  "scss"
]
js: [
  "site.min.js": [
    "libs/sprintf.min.js",
    "libs/bootstrap-transition.js",
    "libs/bootstrap-collapse.js",
    "libs/bootstrap-tooltip.js",
    "libs/imageFlip.js",
    "libs/jquery.cookie.js",
    "libs/jquery.fcbkcomplete.js",
    "libs/jquery.notifier.js",
    "libs/jquery.showLoading.js",
    "libs/jquery.treemap.js",
    "libs/jquery.validate.js",
    "libs/fayer.js",
    "_rexmac.js"
  ]
]
#-----------------------------#
#       Build Settings        #
#-----------------------------#
projects:
  pebble: [
    "chronocode",
    "pingchrong"
  ]
